import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/widgets/gamer_components.dart';

/// Interactive Free Fire Sensitivity & One-Tap Headshot Calibrator
class SensitivitySheet extends StatefulWidget {
  const SensitivitySheet({super.key});

  static void show(BuildContext context) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (ctx) => const SensitivitySheet(),
    );
  }

  @override
  State<SensitivitySheet> createState() => _SensitivitySheetState();
}

class _SensitivitySheetState extends State<SensitivitySheet> {
  double _general = 98;
  double _redDot = 95;
  double _scope2x = 90;
  double _scope4x = 85;
  double _sniper = 55;
  double _freeLook = 65;
  String _selectedDpi = '411 DPI';

  void _copyAllSettings() {
    final text = '''
🎯 Mobin X Free Fire VIP Sensitivity:
- General: ${_general.toInt()}
- Red Dot: ${_redDot.toInt()}
- 2x Scope: ${_scope2x.toInt()}
- 4x Scope: ${_scope4x.toInt()}
- Sniper Scope: ${_sniper.toInt()}
- Free Look: ${_freeLook.toInt()}
- Recommended DPI: $_selectedDpi
⚡ Generated by Mobin X Gaming App
''';
    Clipboard.setData(ClipboardData(text: text));
    Navigator.pop(context);
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('📋 Headshot Sensitivity copied to clipboard!'),
        behavior: SnackBarBehavior.floating,
        backgroundColor: AppColors.primary,
      ),
    );
  }

  void _optimizeSettings() {
    setState(() {
      _general = 100;
      _redDot = 98;
      _scope2x = 94;
      _scope4x = 88;
      _sniper = 50;
      _freeLook = 70;
      _selectedDpi = '440 DPI (Pro Gamer)';
    });
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('⚡ One-Tap Auto Headshot calibration applied!'),
        behavior: SnackBarBehavior.floating,
        backgroundColor: AppColors.emerald,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      constraints: BoxConstraints(
        maxHeight: MediaQuery.of(context).size.height * 0.85,
      ),
      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
      decoration: const BoxDecoration(
        color: AppColors.surfaceCard,
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
        border: Border(top: BorderSide(color: AppColors.cyanLight, width: 2)),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Drag Handle
          Center(
            child: Container(
              width: 42,
              height: 4,
              decoration: BoxDecoration(
                color: AppColors.borderLight,
                borderRadius: BorderRadius.circular(2),
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Title & Badge
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  gradient: AppColors.gamerGlowGradient,
                  borderRadius: BorderRadius.circular(10),
                ),
                child: const Icon(Icons.track_changes_rounded, color: Colors.white, size: 20),
              ),
              const SizedBox(width: 10),
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'SENSITIVITY CALIBRATOR',
                    style: GoogleFonts.outfit(
                      fontSize: 16.5,
                      fontWeight: FontWeight.w900,
                      color: Colors.white,
                      letterSpacing: 0.5,
                    ),
                  ),
                  Text(
                    'One-Tap Drag Headshot & DPI Tuning',
                    style: GoogleFonts.inter(fontSize: 11, color: AppColors.textMuted),
                  ),
                ],
              ),
              const Spacer(),
              const GamerBadge(
                text: 'VIP TOOL',
                color: AppColors.gold,
              ),
            ],
          ),
          const SizedBox(height: 16),

          // Scrollable Sliders
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                children: [
                  _buildSlider('General (সাধারণ)', _general, (val) => setState(() => _general = val)),
                  _buildSlider('Red Dot (রেড ডট)', _redDot, (val) => setState(() => _redDot = val)),
                  _buildSlider('2x Scope (২x স্কোপ)', _scope2x, (val) => setState(() => _scope2x = val)),
                  _buildSlider('4x Scope (৪x স্কোপ)', _scope4x, (val) => setState(() => _scope4x = val)),
                  _buildSlider('Sniper Scope (স্নাইপার)', _sniper, (val) => setState(() => _sniper = val)),
                  _buildSlider('Free Look (ফ্রি লুক)', _freeLook, (val) => setState(() => _freeLook = val)),
                  const SizedBox(height: 10),

                  // Recommended DPI Card
                  GamerCard(
                    padding: const EdgeInsets.all(12),
                    borderColor: AppColors.cyanLight.withValues(alpha: 0.3),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Recommended Phone DPI',
                              style: GoogleFonts.outfit(
                                fontSize: 13,
                                fontWeight: FontWeight.w800,
                                color: Colors.white,
                              ),
                            ),
                            Text(
                              'Set in Android Developer Options',
                              style: GoogleFonts.inter(fontSize: 10.5, color: AppColors.textMuted),
                            ),
                          ],
                        ),
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                          decoration: BoxDecoration(
                            color: AppColors.cyanLight.withValues(alpha: 0.15),
                            borderRadius: BorderRadius.circular(8),
                            border: Border.all(color: AppColors.cyanLight.withValues(alpha: 0.5)),
                          ),
                          child: Text(
                            _selectedDpi,
                            style: GoogleFonts.outfit(
                              fontSize: 12,
                              fontWeight: FontWeight.w900,
                              color: AppColors.cyanLight,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(height: 14),

          // Buttons: Auto Headshot Optimize + Copy
          Row(
            children: [
              Expanded(
                child: OutlinedButton.icon(
                  icon: const Icon(Icons.auto_fix_high_rounded, size: 16, color: AppColors.cyanLight),
                  label: Text(
                    'AUTO TUNE',
                    style: GoogleFonts.outfit(fontWeight: FontWeight.w800, fontSize: 12.5),
                  ),
                  style: OutlinedButton.styleFrom(
                    foregroundColor: AppColors.cyanLight,
                    side: const BorderSide(color: AppColors.cyanLight, width: 1.5),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
                    padding: const EdgeInsets.symmetric(vertical: 12),
                  ),
                  onPressed: _optimizeSettings,
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: GamerButton(
                  label: 'COPY ALL',
                  icon: Icons.copy_rounded,
                  height: 44,
                  onPressed: _copyAllSettings,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildSlider(String label, double value, ValueChanged<double> onChanged) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                label,
                style: GoogleFonts.outfit(
                  fontSize: 13,
                  fontWeight: FontWeight.w700,
                  color: AppColors.textBody,
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                decoration: BoxDecoration(
                  color: AppColors.primary.withValues(alpha: 0.2),
                  borderRadius: BorderRadius.circular(6),
                ),
                child: Text(
                  value.toInt().toString(),
                  style: GoogleFonts.outfit(
                    fontSize: 13,
                    fontWeight: FontWeight.w900,
                    color: AppColors.cyanLight,
                  ),
                ),
              ),
            ],
          ),
          SliderTheme(
            data: SliderTheme.of(context).copyWith(
              activeTrackColor: AppColors.primary,
              inactiveTrackColor: AppColors.surfaceBorder,
              thumbColor: AppColors.cyanLight,
              trackHeight: 4,
              thumbShape: const RoundSliderThumbShape(enabledThumbRadius: 7),
              overlayShape: const RoundSliderOverlayShape(overlayRadius: 14),
            ),
            child: Slider(
              value: value,
              min: 0,
              max: 100,
              onChanged: onChanged,
            ),
          ),
        ],
      ),
    );
  }
}
